### ISSUE TITLE
Handle that some PHP examples starts with <?php

### ISSUE THREAD

**Issue by Nyholm** [symfony-docs-tools/code-block-checker#19]
Normally we prepend all PHP examples with `<?php`, but that fails when the example itself defines that. 

Also, we should not add `<?php` on `html+php`.

**Comment by wouterj** [comment]
Note that we also have some `php`-only code blocks with the `<?php` in them (IIRC, the getting started guides includes them and so do your code examples from the Runtime docs :wink: )
